# ADVANCED NUMPY

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4,5,6]

In [4]:
a

[1, 2, 3, 4, 5, 6]

In [5]:
b=np.array((1,2,3,4,5,6))

In [6]:
b

array([1, 2, 3, 4, 5, 6])

In [5]:
import numpy as np

In [8]:
a=np.array((1,2,3,4))

In [9]:
a

array([1, 2, 3, 4])

In [10]:
a[0]

1

In [11]:
a[-1]

4

# COMPARISON BETWEEN LIST AND ARRAY

3 BENEFITS OF ARRAY

1) TAKES LESS MEMORY

2) FAST

3) CONVININENT

In [2]:
import time
import sys

In [13]:
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [14]:
sys.getsizeof(100)

28

In [15]:
a=np.arange(200000)
print(a.itemsize*len(a))

800000


2) FAST

In [8]:
a1=range(1000000)
b1=range(1000000)

start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print( "time taken :",(time.time()-start)*1000)


time taken : 98.7253189086914


In [10]:
a2=np.arange(1000000)
b2=np.arange(1000000)

start=time.time()
c2= a2+b2
print(" time taken by array :", (time.time()-start)*1000)

 time taken by array : 1.9941329956054688


In [18]:
c2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

3) CONVININENT

In [19]:
n1=np.arange(100)
n2=np.arange(100)


In [20]:
n3=n1+n2
n3

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [21]:
n4=n2-n1
n4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
n5=n2*n1
n5

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [23]:
n6=n2/n1
n6

C:\Users\eshan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# BASIC OPERATIONS

In [24]:
import numpy as np


In [25]:
b=1,2,3

In [26]:
b

(1, 2, 3)

In [27]:
c=np.array(b)

In [28]:
c

array([1, 2, 3])

In [29]:
a=np.array([4,5,6])

In [30]:
a

array([4, 5, 6])

In [31]:
type(np.array([1,2,3]))

numpy.ndarray

In [32]:
c

array([1, 2, 3])

In [33]:
c.ndim

1

In [34]:
b=np.array([[[1, 2, 3]]],ndmin=10)

In [35]:
b

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [36]:
b.ndim

10

In [37]:
a.ndim

1

In [38]:
c=np.array([ 2,9.0,'a',100,9.435,56.9876])

In [39]:
c

array(['2', '9.0', 'a', '100', '9.435', '56.9876'], dtype='<U32')

In [40]:
d=np.dtype('<U11')

In [41]:
d.name

'str352'

In [42]:
d=np.array([1, 2,9.0])

In [43]:
d

array([1., 2., 9.])

In [44]:
a=[1,2,3,[3,4,5]]

In [45]:
b=np.array(a)

C:\Users\eshan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [46]:
b

array([1, 2, 3, list([3, 4, 5])], dtype=object)

In [47]:
a=np.array([[1,2,3],[1,2,3]],ndmin=2)
a

array([[1, 2, 3],
       [1, 2, 3]])

In [48]:
a.ndim

2

In [49]:
a.shape

(2, 3)

In [50]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [51]:
a[0][]

SyntaxError: invalid syntax (<ipython-input-51-1cfeacfc2662>, line 1)

In [52]:
a.itemsize

4

In [53]:
a.size

6

In [54]:
a.dtype

dtype('int32')

In [55]:
a=np.array([[1,2,3,6],[4,5,6,9]],dtype='<f4')

In [56]:
a

array([[1., 2., 3., 6.],
       [4., 5., 6., 9.]], dtype=float32)

In [57]:
a.itemsize

4

In [58]:
a.size

8

In [59]:
a.dtype

dtype('float32')

In [60]:
a

array([[1., 2., 3., 6.],
       [4., 5., 6., 9.]], dtype=float32)

In [61]:
a=np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [62]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [63]:
a.size

6

In [64]:
a.shape

(2, 3)

In [65]:
a=np.array([[1,2,3],[4,5,6]],dtype=complex)

In [66]:
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [67]:
x = np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=[('a','<f8'),('b','<i8'),("c","<U3")])

In [68]:
x[2]

(7., 8, '9')

In [69]:
x[1]

(4., 5, '6')

In [70]:
type(x['a'][1])

numpy.float64

In [71]:
a=np.mat("1 2;3 4")


In [72]:
a

matrix([[1, 2],
        [3, 4]])

In [73]:
a[1]

matrix([[3, 4]])

# SHALLOW AND DEEP COPY

In [74]:
b=np.mat([1,2])
b

matrix([[1, 2]])

In [75]:
c=np.array([1,2],ndmin=2)

In [76]:
c

array([[1, 2]])

In [77]:
c[0][0]

1

In [78]:
b is c

False

In [79]:
id(b)

2361178184840

In [80]:
id(c)

2361190450560

In [81]:
d=b

In [82]:
d

matrix([[1, 2]])

In [83]:
id(b)

2361178184840

In [84]:
id(d)

2361178184840

In [85]:
id(b)

2361178184840

In [86]:
d[0]=10
d

matrix([[10, 10]])

In [87]:
b

matrix([[10, 10]])

In [88]:
e=np.copy(b)

In [89]:
e

array([[10, 10]])

In [90]:
e[0]=20

In [91]:
e

array([[20, 20]])

In [92]:
b

matrix([[10, 10]])

In [93]:
id(e)

2361136212928

In [94]:
id(b)

2361178184840

In [95]:
l=[1,2,3,4,5]

In [96]:
l1=l

In [97]:
l1

[1, 2, 3, 4, 5]

In [98]:
l1[1]=100

In [99]:
l1

[1, 100, 3, 4, 5]

In [100]:
l

[1, 100, 3, 4, 5]

In [101]:
print(id(l1)),print(id(l))

2361178142280
2361178142280


(None, None)

In [102]:
l1[1]=56

In [103]:
l1

[1, 56, 3, 4, 5]

In [104]:
l

[1, 56, 3, 4, 5]

In [105]:
l=[1,2,3,4,5]

In [106]:
l2=l.copy()

In [107]:
l2

[1, 2, 3, 4, 5]

In [108]:
print(id(l),id(l2))

2361178142024 2361190478408


In [109]:
l2[3]=100
l2

[1, 2, 3, 100, 5]

In [110]:
l

[1, 2, 3, 4, 5]

In [111]:
l=[[1,2,3],[4,56]]

In [112]:
l

[[1, 2, 3], [4, 56]]

In [113]:
l2=l.copy()

In [114]:
l2

[[1, 2, 3], [4, 56]]

In [115]:
l2[0][2]=100

In [116]:
l2

[[1, 2, 100], [4, 56]]

In [117]:
l

[[1, 2, 100], [4, 56]]

In [118]:
print(id(l)),print(id(l2))

2361190519112
2361190485384


(None, None)

In [119]:
import copy

In [120]:
l=[[1,2,3],[4,5,6]]

In [121]:
l2=copy.deepcopy(l)

In [122]:
l2

[[1, 2, 3], [4, 5, 6]]

In [123]:
l2[0][2]=100

In [124]:
l2,l

([[1, 2, 100], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]])

# arange and linspace

In [125]:
np.arange(10,100,50)

array([10, 60])

In [130]:
a = np.arange(0,10,1.4)
a

array([0. , 1.4, 2.8, 4.2, 5.6, 7. , 8.4, 9.8])

In [131]:
a[::-1]

array([9.8, 8.4, 7. , 5.6, 4.2, 2.8, 1.4, 0. ])

In [132]:
for i in np.arange(10,20.8,.8):
    print(i)

10.0
10.8
11.600000000000001
12.400000000000002
13.200000000000003
14.000000000000004
14.800000000000004
15.600000000000005
16.400000000000006
17.200000000000006
18.000000000000007
18.800000000000008
19.60000000000001
20.40000000000001


In [133]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [134]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [222]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [135]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [143]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [144]:
np.linspace(1, 10,3, endpoint=False)

array([1., 4., 7.])

In [145]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [146]:
np.linspace(1, 10,5, retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [147]:
np.linspace(2,3,5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [133]:
np.logspace(2.0, 3.0, num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [148]:
np.logspace(2.0, 3.0,5, base=2.0)

array([4.        , 4.75682846, 5.65685425, 6.72717132, 8.        ])

# RESHAPE

In [156]:
x = np.arange(20).reshape(10,2)

In [157]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

# MATRIX CREATION

In [238]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [239]:
np.ones((10,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [240]:
5*np.ones((3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [241]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [159]:
np.eye(2) 

array([[1., 0.],
       [0., 1.]])

# DIAGONAL

In [160]:
x = np.arange(25).reshape(((5,5)))

In [161]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [162]:
np.diag(x)

array([ 0,  6, 12, 18, 24])

In [163]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [165]:
np.diagflat([[1,2,10], [3,4,10]])

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0],
       [ 0,  0, 10,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0, 10]])

An array with ones at and below the given diagonal and zeros elsewhere

# Random number generation

Uniform distribution with random numbers ranging from 0 to 1

In [11]:
np.random.rand(10,5)

array([[0.82706361, 0.83537983, 0.80067107, 0.39185531, 0.91873062],
       [0.67552694, 0.35660472, 0.05161584, 0.86476734, 0.32082562],
       [0.35462051, 0.9275203 , 0.66944815, 0.42903311, 0.99323776],
       [0.73191433, 0.74235438, 0.73492037, 0.08496448, 0.02256712],
       [0.17331472, 0.64845911, 0.33416476, 0.69148365, 0.76898723],
       [0.48773237, 0.90022115, 0.03937843, 0.31434686, 0.68488891],
       [0.29904234, 0.84625283, 0.21186726, 0.00655573, 0.70884422],
       [0.68516312, 0.83633206, 0.45888543, 0.26933696, 0.05523081],
       [0.23459689, 0.70504735, 0.04837916, 0.94505846, 0.89049641],
       [0.20865042, 0.85590463, 0.09222229, 0.95262968, 0.82699597]])

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal

In [168]:
np.random.randn(5,5)

array([[ 0.89262377, -0.82866336, -1.09333881,  0.31087987,  0.35280388],
       [-1.04196372, -1.31946637,  0.58036832, -1.61679808,  0.3061946 ],
       [-2.27197554, -2.37506153,  1.42921504, -0.07998414,  1.63026736],
       [ 0.39124266, -1.96717096,  1.40594157,  0.59201119,  1.45400789],
       [-0.11108193,  1.30491646, -0.28931252, -1.4359521 ,  1.33996361]])

In [12]:
np.random.randint(1,20,12)

array([ 4,  7, 17, 15, 15, 10, 17,  7,  8, 14,  4, 18])

In [13]:
np.random.randint(1,100,(4,5))

array([[78, 28, 26,  1, 16],
       [ 6, 24, 68, 46, 93],
       [ 9, 83, 83, 76, 83],
       [98, 94, 18, 61, 35]])

In [178]:
from numpy.random import randint as ri
a = ri(1,100,30)

c = a.reshape(6,5)

In [252]:
a

array([83, 78, 40,  9, 53, 62, 58, 61, 34, 77,  2, 92, 48, 68, 98, 42, 64,
       52, 59, 49, 80, 52, 88, 39, 13, 69, 20, 10, 17, 96])

In [179]:
c

array([[40, 89, 54, 87, 29],
       [51, 16, 35, 16,  4],
       [46, 36, 32, 66, 54],
       [ 7, 15, 93, 94, 85],
       [82, 35,  3, 35, 78],
       [77, 36, 71, 15,  2]])

In [181]:
M = ri(1,100,25).reshape(5,5)

In [182]:
M

array([[30, 61, 54,  3, 30],
       [94, 72, 11, 85, 89],
       [49, 62, 48, 51, 17],
       [ 9, 20, 50, 35, 61],
       [61, 57, 75, 63, 85]])

In [183]:
np.sort(M, kind='mergesort')

array([[ 3, 30, 30, 54, 61],
       [11, 72, 85, 89, 94],
       [17, 48, 49, 51, 62],
       [ 9, 20, 35, 50, 61],
       [57, 61, 63, 75, 85]])

In [184]:
np.sort(M, axis=0, kind='mergesort')

array([[ 9, 20, 11,  3, 17],
       [30, 57, 48, 35, 30],
       [49, 61, 50, 51, 61],
       [61, 62, 54, 63, 85],
       [94, 72, 75, 85, 89]])

In [185]:
dtype = [('name', '<U32'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)      
 

In [188]:
a["height"]

array([1.8, 1.9, 1.7])

In [190]:
np.sort(a, order='age')

array([('Galahad', 1.7, 38), ('Lancelot', 1.9, 38), ('Arthur', 1.8, 41)],
      dtype=[('name', '<U32'), ('height', '<f8'), ('age', '<i4')])

In [191]:
a = ri(1,100,30)
b = a.reshape(6,5)
b

array([[93, 31, 45, 96, 53],
       [59,  3, 96, 10, 72],
       [74, 79, 17, 89, 37],
       [49, 99, 55, 17, 85],
       [89, 79, 60, 85, 73],
       [60, 43, 10, 68, 78]])

In [192]:
a

array([93, 31, 45, 96, 53, 59,  3, 96, 10, 72, 74, 79, 17, 89, 37, 49, 99,
       55, 17, 85, 89, 79, 60, 85, 73, 60, 43, 10, 68, 78])

In [194]:
a.max()

99

In [195]:
a.min()

3

In [196]:
b.max()

99

In [197]:
b.min()

3

In [198]:
b

array([[93, 31, 45, 96, 53],
       [59,  3, 96, 10, 72],
       [74, 79, 17, 89, 37],
       [49, 99, 55, 17, 85],
       [89, 79, 60, 85, 73],
       [60, 43, 10, 68, 78]])

In [199]:
b.max(axis=1)

array([96, 96, 89, 99, 89, 78])

In [200]:
b.max(axis=0)

array([93, 99, 96, 96, 85])

In [203]:
b

array([[93, 31, 45, 96, 53],
       [59,  3, 96, 10, 72],
       [74, 79, 17, 89, 37],
       [49, 99, 55, 17, 85],
       [89, 79, 60, 85, 73],
       [60, 43, 10, 68, 78]])

In [202]:
b.argmax( )

16

In [205]:
b.argmax(axis=1)

array([3, 2, 3, 1, 0, 4], dtype=int64)

# Indexing and slicing

In [206]:
arr = np.arange(0,11)

In [207]:
arr[0]

0

In [208]:
arr[3:6]

array([3, 4, 5])

In [209]:
arr[:4]

array([0, 1, 2, 3])

In [210]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [211]:
arr[[2,4,9]]

array([ 4,  8, 18])

In [218]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[49, 92, 78, 71, 17],
       [35, 36, 68, 74, 26],
       [74, 94, 90, 91, 51]])

In [214]:
mat[1][2]

81

In [215]:
mat[1,2]

81

In [216]:
mat[2]

array([42, 77, 63, 47, 32])

In [219]:
mat[0:2,0:2]

array([[49, 92],
       [35, 36]])

Matrix with row indices 0 and 1 and column indices 1 and 3

In [224]:
mat[:,]

array([[49, 92, 78, 71, 17],
       [35, 36, 68, 74, 26],
       [74, 94, 90, 91, 51]])

# Subseting

In [225]:
mat = np.array(ri(10,100,15)).reshape(3,5)

In [226]:
mat

array([[22, 38, 20, 46, 94],
       [88, 78, 48, 59, 90],
       [48, 95, 27, 20, 34]])

In [228]:
mat[mat<50]

array([22, 38, 20, 46, 48, 48, 27, 20, 34])

In [231]:
mat[mat!=50]

array([22, 38, 20, 46, 94, 88, 78, 48, 59, 90, 48, 95, 27, 20, 34])

In [232]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [233]:
mat_slice = mat[:2,:2]
mat_slice

array([[11, 12],
       [21, 22]])

In [234]:
mat_slice[0,0] = 1000
mat_slice

array([[1000,   12],
       [  21,   22]])

In [235]:
mat

array([[1000,   12,   13],
       [  21,   22,   23],
       [  31,   32,   33]])

In [236]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [237]:
mat_slice = np.array(mat[:2,:2])

In [238]:
mat_slice[0,0] = 1000

In [239]:
mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# Universal Functions

In [240]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

In [241]:
mat1

array([[3, 7, 8],
       [7, 5, 2],
       [1, 1, 4]])

In [242]:
mat2

array([[6, 7, 8],
       [4, 1, 9],
       [2, 9, 2]])

In [243]:
mat1+mat2

array([[ 9, 14, 16],
       [11,  6, 11],
       [ 3, 10,  6]])

In [244]:
mat1*mat2

array([[18, 49, 64],
       [28,  5, 18],
       [ 2,  9,  8]])

In [245]:
mat1/mat2

array([[0.5       , 1.        , 1.        ],
       [1.75      , 5.        , 0.22222222],
       [0.5       , 0.11111111, 2.        ]])

In [246]:
3*mat1-2*mat2

array([[ -3,   7,   8],
       [ 13,  13, -12],
       [ -1, -15,   8]])

In [247]:
100+mat1

array([[103, 107, 108],
       [107, 105, 102],
       [101, 101, 104]])

In [248]:
mat1**3

array([[ 27, 343, 512],
       [343, 125,   8],
       [  1,   1,  64]], dtype=int32)

In [249]:
pow(mat1,0.5)

array([[1.73205081, 2.64575131, 2.82842712],
       [2.64575131, 2.23606798, 1.41421356],
       [1.        , 1.        , 2.        ]])

# Broadcasting

In [250]:
start = np.zeros((3,3))

In [251]:
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [252]:
add_rows = np.array([1, 0, 2])

In [253]:
add_rows

array([1, 0, 2])

In [255]:
y = start + add_rows

In [256]:
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [257]:
add_cols = np.array([[0,1,2,3]])
add_cols

array([[0, 1, 2, 3]])

In [258]:
add_cols = add_cols.T

In [259]:
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [336]:
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [260]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [261]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [312]:
b=np.array([[10,20,30]])

In [313]:
b

array([[10, 20, 30]])

In [314]:
c=b.T

In [316]:
np.hstack((a,c))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [265]:
a+b

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])